import * as React from "react";
import Link from "next/link";
import { Cpu, Lightbulb, Link2, Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tooltip } from "@/components/ui/tooltip";
import { RiskPill } from "./risk-score";
import { SeverityBadge } from "./indicators";
import { formatRelative } from "@/lib/utils/format";
import type { CorrelatedEvent } from "@/lib/ai/automation";

/**
 * AI analysis panels (§21).
 *
 * Every panel states whether it was generated by a model or computed
 * deterministically. An analyst acting on machine-written text is entitled to
 * know which kind it is — and the distinction matters more here than in most
 * products, because the deterministic version is not a degraded fallback but a
 * different epistemic claim.
 */

function ProvenanceBadge({ fromModel }: { fromModel: boolean }) {
  return (
    <Tooltip
      content={
        fromModel
          ? "Generated by a language model from this incident's recorded data. Advisory only — it cannot change any decision the engine made."
          : "Computed deterministically from the recorded data. No model was involved, so the same inputs always produce this text."
      }
    >
      <Badge tone={fromModel ? "brand" : "neutral"} size="xs">
        {fromModel ? <Sparkles /> : <Cpu />}
        {fromModel ? "AI generated" : "Deterministic"}
      </Badge>
    </Tooltip>
  );
}

export function AiSummaryCard({
  summary,
  fromModel,
  title = "Analysis",
}: {
  summary: string;
  fromModel: boolean;
  title?: string;
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="size-3.5 text-brand" />
          {title}
        </CardTitle>
        <ProvenanceBadge fromModel={fromModel} />
      </CardHeader>
      <CardContent>
        <p className="whitespace-pre-wrap text-xs leading-relaxed text-ink-2">{summary}</p>
      </CardContent>
    </Card>
  );
}

export function AiRecommendationsCard({
  items,
  fromModel,
}: {
  items: string[];
  fromModel: boolean;
}) {
  if (items.length === 0) return null;

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="size-3.5 text-medium" />
          Suggested mitigations
        </CardTitle>
        <ProvenanceBadge fromModel={fromModel} />
      </CardHeader>
      <CardContent>
        <ol className="space-y-2">
          {items.map((item, i) => (
            <li key={i} className="flex gap-2.5 rounded-md border border-line bg-surface-2/40 px-3 py-2">
              <span className="mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full bg-inset font-mono text-[9px] text-ink-4">
                {i + 1}
              </span>
              <span className="text-[11px] leading-relaxed text-ink-2">{item}</span>
            </li>
          ))}
        </ol>
        <p className="mt-3 text-[10px] leading-relaxed text-ink-4">
          Advisory. Nothing here has been applied — mitigations are an analyst decision, recorded
          on the incident timeline when acted on.
        </p>
      </CardContent>
    </Card>
  );
}

export function CorrelatedEventsCard({ events }: { events: CorrelatedEvent[] }) {
  if (events.length === 0) return null;

  return (
    <Card>
      <CardHeader>
        <div>
          <CardTitle className="flex items-center gap-2">
            <Link2 className="size-3.5 text-brand" />
            Related activity
          </CardTitle>
          <p className="mt-0.5 text-xs text-ink-3">
            Events sharing a principal, agent, threat type or document within six hours.
          </p>
        </div>
        <Badge tone="neutral" size="xs">{events.length}</Badge>
      </CardHeader>
      <CardContent>
        <ul className="space-y-2">
          {events.map((e) => (
            <li key={e.id}>
              <Link
                href={`/monitor/${e.id}`}
                className="block rounded-md border border-line bg-surface-2/40 p-2.5 transition-colors hover:border-line-strong hover:bg-surface-2"
              >
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="flex items-center gap-2">
                    <span className="font-mono text-[10px] text-ink-4">{e.ref}</span>
                    {e.user && <span className="text-[11px] text-ink-2">{e.user}</span>}
                    <span className="text-[10px] text-ink-4">{formatRelative(e.createdAt)}</span>
                  </span>
                  <span className="flex items-center gap-1.5">
                    <SeverityBadge severity={e.severity} size="xs" showIcon={false} withTooltip={false} />
                    <RiskPill score={e.riskScore} />
                  </span>
                </div>

                <p className="mt-1 truncate text-[11px] text-ink-3">{e.requestExcerpt}</p>

                <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
                  {e.reasons.map((r) => (
                    <span key={r} className="rounded bg-inset px-1.5 py-px text-[9px] text-ink-4">
                      {r}
                    </span>
                  ))}
                  <span className="ml-auto font-mono text-[9px] text-ink-4">
                    {(e.strength * 100).toFixed(0)}% link strength
                  </span>
                </div>
              </Link>
            </li>
          ))}
        </ul>
        <p className="mt-3 text-[10px] leading-relaxed text-ink-4">
          Correlation is computed deterministically from shared attributes, not inferred by a
          model — a hallucinated link during an investigation is worse than no link at all.
        </p>
      </CardContent>
    </Card>
  );
}
